# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galfitWidgetBD.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(515, 700)
        font = QtGui.QFont()
        font.setFamily("EB Garamond")
        font.setPointSize(10)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.mainframe = QtWidgets.QFrame(Form)
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainframe)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.mainframe)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2.addWidget(self.widget_7, 5, 3, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.mainframe)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2.addWidget(self.widget_8, 3, 3, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.mainframe)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_2.addWidget(self.widget_14, 1, 3, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.mainframe)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2.addWidget(self.widget_6, 0, 3, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.mainframe)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_2.addWidget(self.widget_10, 4, 3, 1, 1)
        self.cutouts = QtWidgets.QFrame(self.mainframe)
        self.cutouts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cutouts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cutouts.setObjectName("cutouts")
        self.cutoutsLayout = QtWidgets.QGridLayout(self.cutouts)
        self.cutoutsLayout.setObjectName("cutoutsLayout")
        self.dummyWidget = QtWidgets.QWidget(self.cutouts)
        self.dummyWidget.setObjectName("dummyWidget")
        self.cutoutsLayout.addWidget(self.dummyWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.cutouts, 0, 0, 9, 3)
        self.frame = QtWidgets.QFrame(self.mainframe)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ReLineEdit = QtWidgets.QLineEdit(self.frame)
        self.ReLineEdit.setObjectName("ReLineEdit")
        self.gridLayout_3.addWidget(self.ReLineEdit, 6, 1, 1, 1)
        self.magLineEdit = QtWidgets.QLineEdit(self.frame)
        self.magLineEdit.setObjectName("magLineEdit")
        self.gridLayout_3.addWidget(self.magLineEdit, 5, 1, 1, 1)
        self.widget_20 = QtWidgets.QWidget(self.frame)
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.widget_20)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_20, 1, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 9, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 9, 0, 1, 1)
        self.xcLineEdit = QtWidgets.QLineEdit(self.frame)
        self.xcLineEdit.setObjectName("xcLineEdit")
        self.gridLayout_3.addWidget(self.xcLineEdit, 3, 1, 1, 1)
        self.n2LineEdit = QtWidgets.QLineEdit(self.frame)
        self.n2LineEdit.setObjectName("n2LineEdit")
        self.gridLayout_3.addWidget(self.n2LineEdit, 7, 3, 1, 1)
        self.nLineEdit = QtWidgets.QLineEdit(self.frame)
        self.nLineEdit.setObjectName("nLineEdit")
        self.gridLayout_3.addWidget(self.nLineEdit, 7, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 5, 2, 1, 1)
        self.Re2LineEdit = QtWidgets.QLineEdit(self.frame)
        self.Re2LineEdit.setObjectName("Re2LineEdit")
        self.gridLayout_3.addWidget(self.Re2LineEdit, 6, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 6, 0, 1, 1)
        self.BA2LineEdit = QtWidgets.QLineEdit(self.frame)
        self.BA2LineEdit.setObjectName("BA2LineEdit")
        self.gridLayout_3.addWidget(self.BA2LineEdit, 9, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 7, 0, 1, 1)
        self.PA2LineEdit = QtWidgets.QLineEdit(self.frame)
        self.PA2LineEdit.setObjectName("PA2LineEdit")
        self.gridLayout_3.addWidget(self.PA2LineEdit, 8, 3, 1, 1)
        self.PALineEdit = QtWidgets.QLineEdit(self.frame)
        self.PALineEdit.setObjectName("PALineEdit")
        self.gridLayout_3.addWidget(self.PALineEdit, 8, 1, 1, 1)
        self.BALineEdit = QtWidgets.QLineEdit(self.frame)
        self.BALineEdit.setObjectName("BALineEdit")
        self.gridLayout_3.addWidget(self.BALineEdit, 9, 1, 1, 1)
        self.mag2LineEdit = QtWidgets.QLineEdit(self.frame)
        self.mag2LineEdit.setObjectName("mag2LineEdit")
        self.gridLayout_3.addWidget(self.mag2LineEdit, 5, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 7, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 8, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.ycLineEdit = QtWidgets.QLineEdit(self.frame)
        self.ycLineEdit.setObjectName("ycLineEdit")
        self.gridLayout_3.addWidget(self.ycLineEdit, 4, 1, 1, 1)
        self.xc2LineEdit = QtWidgets.QLineEdit(self.frame)
        self.xc2LineEdit.setObjectName("xc2LineEdit")
        self.gridLayout_3.addWidget(self.xc2LineEdit, 3, 3, 1, 1)
        self.yc2LineEdit = QtWidgets.QLineEdit(self.frame)
        self.yc2LineEdit.setObjectName("yc2LineEdit")
        self.gridLayout_3.addWidget(self.yc2LineEdit, 4, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 3, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 4, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 12, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.mainframe)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runGalfitButton = QtWidgets.QPushButton(self.frame_4)
        self.runGalfitButton.setObjectName("runGalfitButton")
        self.horizontalLayout.addWidget(self.runGalfitButton)
        self.helpButton = QtWidgets.QPushButton(self.frame_4)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout.addWidget(self.helpButton)
        self.quitButton = QtWidgets.QPushButton(self.frame_4)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout.addWidget(self.quitButton)
        self.gridLayout_2.addWidget(self.frame_4, 11, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.mainframe)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 10, 0, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.mainframe)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_2.addWidget(self.widget_9, 6, 3, 1, 1)
        self.readoutframe = QtWidgets.QFrame(self.mainframe)
        self.readoutframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.readoutframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.readoutframe.setObjectName("readoutframe")
        self.readoutGridLayout = QtWidgets.QGridLayout(self.readoutframe)
        self.readoutGridLayout.setObjectName("readoutGridLayout")
        self.gridLayout_2.addWidget(self.readoutframe, 9, 0, 1, 3)
        self.widget_15 = QtWidgets.QWidget(self.mainframe)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_2.addWidget(self.widget_15, 2, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.mainframe)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 7, 3, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.mainframe)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.errorFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.errorFitLineEdit.setObjectName("errorFitLineEdit")
        self.gridLayout_4.addWidget(self.errorFitLineEdit, 12, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.widget_21 = QtWidgets.QWidget(self.frame_3)
        self.widget_21.setObjectName("widget_21")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_21)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_16 = QtWidgets.QLabel(self.widget_21)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_21, 1, 0, 1, 7)
        self.asymLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.asymLineEdit.setObjectName("asymLineEdit")
        self.gridLayout_4.addWidget(self.asymLineEdit, 9, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 8, 0, 1, 1)
        self.ycFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.ycFitLineEdit.setObjectName("ycFitLineEdit")
        self.gridLayout_4.addWidget(self.ycFitLineEdit, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.xcFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.xcFitLineEdit.setObjectName("xcFitLineEdit")
        self.gridLayout_4.addWidget(self.xcFitLineEdit, 2, 2, 1, 1)
        self.magFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.magFitLineEdit.setObjectName("magFitLineEdit")
        self.gridLayout_4.addWidget(self.magFitLineEdit, 4, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 12, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 8, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 5, 3, 1, 1)
        self.nFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.nFitLineEdit.setObjectName("nFitLineEdit")
        self.gridLayout_4.addWidget(self.nFitLineEdit, 6, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 6, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 7, 3, 1, 1)
        self.ReFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.ReFitLineEdit.setObjectName("ReFitLineEdit")
        self.gridLayout_4.addWidget(self.ReFitLineEdit, 5, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 4, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 3, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 12, 3, 1, 1)
        self.chiFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.chiFitLineEdit.setObjectName("chiFitLineEdit")
        self.gridLayout_4.addWidget(self.chiFitLineEdit, 12, 5, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 9, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 2, 3, 1, 1)
        self.Re2FitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.Re2FitLineEdit.setObjectName("Re2FitLineEdit")
        self.gridLayout_4.addWidget(self.Re2FitLineEdit, 5, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 5, 0, 1, 1)
        self.BAFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.BAFitLineEdit.setObjectName("BAFitLineEdit")
        self.gridLayout_4.addWidget(self.BAFitLineEdit, 8, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 6, 0, 1, 1)
        self.xc2FitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.xc2FitLineEdit.setObjectName("xc2FitLineEdit")
        self.gridLayout_4.addWidget(self.xc2FitLineEdit, 2, 5, 1, 1)
        self.mag2FitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.mag2FitLineEdit.setObjectName("mag2FitLineEdit")
        self.gridLayout_4.addWidget(self.mag2FitLineEdit, 4, 5, 1, 1)
        self.PA2FitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.PA2FitLineEdit.setObjectName("PA2FitLineEdit")
        self.gridLayout_4.addWidget(self.PA2FitLineEdit, 7, 5, 1, 1)
        self.yc2FitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.yc2FitLineEdit.setObjectName("yc2FitLineEdit")
        self.gridLayout_4.addWidget(self.yc2FitLineEdit, 3, 5, 1, 1)
        self.PAFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.PAFitLineEdit.setObjectName("PAFitLineEdit")
        self.gridLayout_4.addWidget(self.PAFitLineEdit, 7, 2, 1, 1)
        self.BA2FitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.BA2FitLineEdit.setObjectName("BA2FitLineEdit")
        self.gridLayout_4.addWidget(self.BA2FitLineEdit, 8, 5, 1, 1)
        self.n2FitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.n2FitLineEdit.setObjectName("n2FitLineEdit")
        self.gridLayout_4.addWidget(self.n2FitLineEdit, 6, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 10, 0, 1, 1)
        self.asymPALineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.asymPALineEdit.setObjectName("asymPALineEdit")
        self.gridLayout_4.addWidget(self.asymPALineEdit, 10, 2, 1, 1)
        self.skyFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.skyFitLineEdit.setObjectName("skyFitLineEdit")
        self.gridLayout_4.addWidget(self.skyFitLineEdit, 10, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 10, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 11, 1, 2, 1)
        self.widget_13 = QtWidgets.QWidget(self.mainframe)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_2.addWidget(self.widget_13, 10, 1, 1, 1)
        self.gridLayout.addWidget(self.mainframe, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "INITIAL PARAMETERS"))
        self.label_3.setText(_translate("Form", "mag"))
        self.label_26.setText(_translate("Form", "B/A2"))
        self.label_7.setText(_translate("Form", "B/A"))
        self.label_22.setText(_translate("Form", "mag2"))
        self.label_6.setText(_translate("Form", "PA"))
        self.label_4.setText(_translate("Form", "Re"))
        self.label_5.setText(_translate("Form", "n"))
        self.label_24.setText(_translate("Form", "n2"))
        self.label_23.setText(_translate("Form", "Re2"))
        self.label.setText(_translate("Form", "xc"))
        self.label_25.setText(_translate("Form", "PA2"))
        self.label_2.setText(_translate("Form", "yc"))
        self.label_34.setText(_translate("Form", "xc2"))
        self.label_35.setText(_translate("Form", "yc2"))
        self.runGalfitButton.setText(_translate("Form", "Run galfit"))
        self.helpButton.setText(_translate("Form", "Help"))
        self.quitButton.setText(_translate("Form", "Quit"))
        self.label_9.setText(_translate("Form", "xc"))
        self.label_16.setText(_translate("Form", "FITTED PARAMETERS"))
        self.label_15.setText(_translate("Form", "B/A"))
        self.label_10.setText(_translate("Form", "yc"))
        self.label_12.setText(_translate("Form", "PA"))
        self.label_11.setText(_translate("Form", "mag"))
        self.label_18.setText(_translate("Form", "error"))
        self.label_31.setText(_translate("Form", "B/A2"))
        self.label_28.setText(_translate("Form", "Re2"))
        self.label_29.setText(_translate("Form", "n2"))
        self.label_30.setText(_translate("Form", "PA2"))
        self.label_27.setText(_translate("Form", "mag2"))
        self.label_21.setText(_translate("Form", "yc2"))
        self.label_19.setText(_translate("Form", "Chi"))
        self.label_32.setText(_translate("Form", "asym"))
        self.label_20.setText(_translate("Form", "xc2"))
        self.label_14.setText(_translate("Form", "Re"))
        self.label_13.setText(_translate("Form", "n"))
        self.label_33.setText(_translate("Form", "aPA"))
        self.label_17.setText(_translate("Form", "sky"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

