# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'halphacutouts.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cutoutFrame = QtWidgets.QFrame(self.centralwidget)
        self.cutoutFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cutoutFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cutoutFrame.setObjectName("cutoutFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cutoutFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cutouts = QtWidgets.QWidget(self.cutoutFrame)
        self.cutouts.setMinimumSize(QtCore.QSize(0, 172))
        self.cutouts.setObjectName("cutouts")
        self.cutoutsLayout = QtWidgets.QGridLayout(self.cutouts)
        self.cutoutsLayout.setObjectName("cutoutsLayout")
        self.gridLayout_2.addWidget(self.cutouts, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.cutoutFrame)
        self.rightFrame = QtWidgets.QFrame(self.centralwidget)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.rightFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.rightFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
       self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 2)
        self.rightButtons = QtWidgets.QWidget(self.rightFrame)
        self.rightButtons.setObjectName("rightButtons")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.rightButtons)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.rightButtons)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ratioSliderLabel = QtWidgets.QLabel(self.frame)
        self.ratioSliderLabel.setObjectName("ratioSliderLabel")
        self.verticalLayout_2.addWidget(self.ratioSliderLabel, 0, QtCore.Qt.AlignHCenter)
        self.filterRatioLineEdit = QtWidgets.QLineEdit(self.frame)
        self.filterRatioLineEdit.setObjectName("filterRatioLineEdit")
        self.verticalLayout_2.addWidget(self.filterRatioLineEdit)
        self.resetRatioButton = QtWidgets.QPushButton(self.frame)
        self.resetRatioButton.setObjectName("resetRatioButton")
        self.verticalLayout_2.addWidget(self.resetRatioButton)
        self.gridLayout_4.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.rightButtons)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cutoutSliderLabel = QtWidgets.QLabel(self.frame_2)
        self.cutoutSliderLabel.setObjectName("cutoutSliderLabel")
        self.verticalLayout.addWidget(self.cutoutSliderLabel, 0, QtCore.Qt.AlignHCenter)
        self.cutoutSizeLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.cutoutSizeLineEdit.setObjectName("cutoutSizeLineEdit")
        self.verticalLayout.addWidget(self.cutoutSizeLineEdit)
        self.resetSizeButton = QtWidgets.QPushButton(self.frame_2)
        self.resetSizeButton.setObjectName("resetSizeButton")
        self.verticalLayout.addWidget(self.resetSizeButton)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.rightButtons)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.makeMaskButton = QtWidgets.QPushButton(self.widget_2)
        self.makeMaskButton.setObjectName("makeMaskButton")
        self.verticalLayout_3.addWidget(self.makeMaskButton)
        self.saveButton = QtWidgets.QPushButton(self.widget_2)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_3.addWidget(self.saveButton)
        self.clearCutoutsButton = QtWidgets.QPushButton(self.widget_2)
        self.clearCutoutsButton.setObjectName("clearCutoutsButton")
        self.verticalLayout_3.addWidget(self.clearCutoutsButton)
        self.gridLayout_4.addWidget(self.widget_2, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.rightButtons)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.haTypeComboBox = QtWidgets.QComboBox(self.frame_5)
        self.haTypeComboBox.setAutoFillBackground(False)
        self.haTypeComboBox.setProperty("currentText", "")
        self.haTypeComboBox.setObjectName("haTypeComboBox")
        self.verticalLayout_6.addWidget(self.haTypeComboBox)
        self.gridLayout_4.addWidget(self.frame_5, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.rightButtons)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.commentLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.commentLineEdit.setObjectName("commentLineEdit")
        self.horizontalLayout_3.addWidget(self.commentLineEdit)
        self.commentComboBox = QtWidgets.QComboBox(self.frame_6)
        self.commentComboBox.setObjectName("commentComboBox")
        self.horizontalLayout_3.addWidget(self.commentComboBox)
        self.gridLayout_4.addWidget(self.frame_6, 6, 0, 1, 2)
        self.frame_4 = QtWidgets.QFrame(self.rightButtons)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.galfitAsymButton = QtWidgets.QPushButton(self.frame_4)
        self.galfitAsymButton.setObjectName("galfitAsymButton")
        self.gridLayout_3.addWidget(self.galfitAsymButton, 1, 0, 1, 1)
        self.galfitButton = QtWidgets.QPushButton(self.frame_4)
        self.galfitButton.setObjectName("galfitButton")
        self.gridLayout_3.addWidget(self.galfitButton, 0, 0, 1, 1)
        self.galfitHaButton = QtWidgets.QPushButton(self.frame_4)
        self.galfitHaButton.setObjectName("galfitHaButton")
        self.gridLayout_3.addWidget(self.galfitHaButton, 0, 1, 1, 1)
        self.galfit2Button = QtWidgets.QPushButton(self.frame_4)
        self.galfit2Button.setObjectName("galfit2Button")
        self.gridLayout_3.addWidget(self.galfit2Button, 2, 0, 1, 1)
        self.galfitHaAsymButton = QtWidgets.QPushButton(self.frame_4)
        self.galfitHaAsymButton.setObjectName("galfitHaAsymButton")
        self.gridLayout_3.addWidget(self.galfitHaAsymButton, 1, 1, 1, 1)
        self.fitEllipseGalfitButton = QtWidgets.QPushButton(self.frame_4)
        self.fitEllipseGalfitButton.setObjectName("fitEllipseGalfitButton")
        self.gridLayout_3.addWidget(self.fitEllipseGalfitButton, 0, 2, 1, 1)
        self.fitEllipsePhotutilsButton = QtWidgets.QPushButton(self.frame_4)
        self.fitEllipsePhotutilsButton.setObjectName("fitEllipsePhotutilsButton")
        self.gridLayout_3.addWidget(self.fitEllipsePhotutilsButton, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.rightButtons, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.rightFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 22))
        self.menubar.setObjectName("menubar")
        self.menuSetup = QtWidgets.QMenu(self.menubar)
        self.menuSetup.setObjectName("menuSetup")
        self.menuHalpha_Filter = QtWidgets.QMenu(self.menubar)
        self.menuHalpha_Filter.setObjectName("menuHalpha_Filter")
        MainWindow.setMenuBar(self.menubar)
        self.action_rcoadd = QtWidgets.QAction(MainWindow)
        self.action_rcoadd.setObjectName("action_rcoadd")
        self.action_hacoadd = QtWidgets.QAction(MainWindow)
        self.action_hacoadd.setObjectName("action_hacoadd")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.action_nsapath = QtWidgets.QAction(MainWindow)
        self.action_nsapath.setObjectName("action_nsapath")
        self.actionha4 = QtWidgets.QAction(MainWindow)
        self.actionha4.setObjectName("actionha4")
        self.actionha8 = QtWidgets.QAction(MainWindow)
        self.actionha8.setObjectName("actionha8")
        self.actionha12 = QtWidgets.QAction(MainWindow)
        self.actionha12.setObjectName("actionha12")
        self.actionha16 = QtWidgets.QAction(MainWindow)
        self.actionha16.setObjectName("actionha16")
        self.actionR_coadd = QtWidgets.QAction(MainWindow)
        self.actionR_coadd.setCheckable(False)
        self.actionR_coadd.setObjectName("actionR_coadd")
        self.actionHa_coadd = QtWidgets.QAction(MainWindow)
        self.actionHa_coadd.setObjectName("actionHa_coadd")
        self.actionHa_coadd_2 = QtWidgets.QAction(MainWindow)
        self.actionHa_coadd_2.setObjectName("actionHa_coadd_2")
        self.actionNSA_catalog_path = QtWidgets.QAction(MainWindow)
        self.actionNSA_catalog_path.setObjectName("actionNSA_catalog_path")
        self.actionQuit_2 = QtWidgets.QAction(MainWindow)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.actionhalpha4 = QtWidgets.QAction(MainWindow)
        self.actionhalpha4.setCheckable(True)
        self.actionhalpha4.setObjectName("actionhalpha4")
        self.actionhalpha8 = QtWidgets.QAction(MainWindow)
        self.actionhalpha8.setCheckable(True)
        self.actionhalpha8.setObjectName("actionhalpha8")
        self.actionhalpha12 = QtWidgets.QAction(MainWindow)
        self.actionhalpha12.setCheckable(True)
        self.actionhalpha12.setObjectName("actionhalpha12")
        self.actionhalpha16 = QtWidgets.QAction(MainWindow)
        self.actionhalpha16.setCheckable(True)
        self.actionhalpha16.setObjectName("actionhalpha16")
        self.actionAGC_catalog_path = QtWidgets.QAction(MainWindow)
        self.actionAGC_catalog_path.setObjectName("actionAGC_catalog_path")
        self.actioninthalpha = QtWidgets.QAction(MainWindow)
        self.actioninthalpha.setCheckable(True)
        self.actioninthalpha.setObjectName("actioninthalpha")
        self.actionintha6657 = QtWidgets.QAction(MainWindow)
        self.actionintha6657.setCheckable(True)
        self.actionintha6657.setObjectName("actionintha6657")
        self.menuSetup.addAction(self.actionR_coadd)
        self.menuSetup.addAction(self.actionHa_coadd_2)
        self.menuSetup.addAction(self.actionNSA_catalog_path)
        self.menuSetup.addAction(self.actionAGC_catalog_path)
        self.menuSetup.addSeparator()
        self.menuSetup.addAction(self.actionQuit_2)
        self.menuHalpha_Filter.addAction(self.actionhalpha4)
        self.menuHalpha_Filter.addAction(self.actionhalpha8)
        self.menuHalpha_Filter.addAction(self.actionhalpha12)
        self.menuHalpha_Filter.addAction(self.actionhalpha16)
        self.menuHalpha_Filter.addAction(self.actioninthalpha)
        self.menuHalpha_Filter.addAction(self.actionintha6657)
        self.menubar.addAction(self.menuSetup.menuAction())
        self.menubar.addAction(self.menuHalpha_Filter.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Halpha Console"))
        self.ratioSliderLabel.setText(_translate("MainWindow", "filter ratio"))
        self.resetRatioButton.setText(_translate("MainWindow", "Reset Filter Ratio"))
        self.cutoutSliderLabel.setText(_translate("MainWindow", "cutout size"))
        self.resetSizeButton.setText(_translate("MainWindow", "Reset Cutout Size"))
        self.makeMaskButton.setText(_translate("MainWindow", "Make and Edit Mask"))
        self.saveButton.setText(_translate("MainWindow", "Save Galaxy"))
        self.clearCutoutsButton.setText(_translate("MainWindow", "Clear Cutouts"))
        self.label_2.setText(_translate("MainWindow", "Classify Halpha"))
        self.haTypeComboBox.setToolTip(_translate("MainWindow", "HalphaType"))
        self.label_3.setText(_translate("MainWindow", "COMMENTS"))
        self.galfitAsymButton.setText(_translate("MainWindow", "galfit 1 + asym"))
        self.galfitButton.setText(_translate("MainWindow", "galfit 1 comp R"))
        self.galfitHaButton.setText(_translate("MainWindow", "galfit 1 comp Ha"))
        self.galfit2Button.setText(_translate("MainWindow", "galfit 2 comp"))
        self.galfitHaAsymButton.setText(_translate("MainWindow", "galfit Ha +asym"))
        self.fitEllipseGalfitButton.setText(_translate("MainWindow", "Ellip Phot (galfit)"))
        self.fitEllipsePhotutilsButton.setText(_translate("MainWindow", "Ellip Phot (photutils)"))
        self.menuSetup.setTitle(_translate("MainWindow", "Setup"))
        self.menuHalpha_Filter.setTitle(_translate("MainWindow", "Halpha Filter"))
        self.action_rcoadd.setText(_translate("MainWindow", "R-band coadd"))
        self.action_hacoadd.setText(_translate("MainWindow", "Halpha coadd"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.action_nsapath.setText(_translate("MainWindow", "set_path"))
        self.actionha4.setText(_translate("MainWindow", "ha4"))
        self.actionha8.setText(_translate("MainWindow", "ha8"))
        self.actionha12.setText(_translate("MainWindow", "ha12"))
        self.actionha16.setText(_translate("MainWindow", "ha16"))
        self.actionR_coadd.setText(_translate("MainWindow", "R coadd path"))
        self.actionR_coadd.setStatusTip(_translate("MainWindow", "full path of R-band coadded image"))
        self.actionHa_coadd.setText(_translate("MainWindow", "Ha coadd path"))
        self.actionHa_coadd.setWhatsThis(_translate("MainWindow", "full path to Halpha coadd image"))
        self.actionHa_coadd_2.setText(_translate("MainWindow", "Ha coadd path"))
        self.actionHa_coadd_2.setStatusTip(_translate("MainWindow", "select Halpha coadded image"))
        self.actionNSA_catalog_path.setText(_translate("MainWindow", "NSA catalog path"))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit"))
        self.actionhalpha4.setText(_translate("MainWindow", "halpha4"))
        self.actionhalpha8.setText(_translate("MainWindow", "halpha8"))
        self.actionhalpha12.setText(_translate("MainWindow", "halpha12"))
        self.actionhalpha16.setText(_translate("MainWindow", "halpha16"))
        self.actionAGC_catalog_path.setText(_translate("MainWindow", "AGC catalog path"))
        self.actioninthalpha.setText(_translate("MainWindow", "int-halpha"))
        self.actionintha6657.setText(_translate("MainWindow", "int-ha6657"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

