# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maskWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        font = QtGui.QFont()
        font.setFamily("EB Garamond")
        font.setPointSize(10)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.mainframe = QtWidgets.QFrame(Form)
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainframe)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_10 = QtWidgets.QWidget(self.mainframe)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_2.addWidget(self.widget_10, 4, 3, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.mainframe)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_2.addWidget(self.widget_9, 6, 3, 1, 1)
        self.buttonWidget = QtWidgets.QWidget(self.mainframe)
        self.buttonWidget.setMouseTracking(True)
        self.buttonWidget.setObjectName("buttonWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.buttonWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mrunSEButton = QtWidgets.QPushButton(self.buttonWidget)
        self.mrunSEButton.setObjectName("mrunSEButton")
        self.gridLayout_3.addWidget(self.mrunSEButton, 0, 3, 1, 1)
        self.mhelpButton = QtWidgets.QPushButton(self.buttonWidget)
        self.mhelpButton.setObjectName("mhelpButton")
        self.gridLayout_3.addWidget(self.mhelpButton, 1, 3, 1, 1)
        self.mquitButton = QtWidgets.QPushButton(self.buttonWidget)
        self.mquitButton.setObjectName("mquitButton")
        self.gridLayout_3.addWidget(self.mquitButton, 2, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.buttonWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.boxSizeLineEdit = QtWidgets.QLineEdit(self.frame)
        self.boxSizeLineEdit.setObjectName("boxSizeLineEdit")
        self.gridLayout_4.addWidget(self.boxSizeLineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.seThresholdLineEdit = QtWidgets.QLineEdit(self.frame)
        self.seThresholdLineEdit.setObjectName("seThresholdLineEdit")
        self.gridLayout_4.addWidget(self.seThresholdLineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.seSNRLineEdit = QtWidgets.QLineEdit(self.frame)
        self.seSNRLineEdit.setObjectName("seSNRLineEdit")
        self.gridLayout_4.addWidget(self.seSNRLineEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.seSNRAnalysisLineEdit = QtWidgets.QLineEdit(self.frame)
        self.seSNRAnalysisLineEdit.setObjectName("seSNRAnalysisLineEdit")
        self.gridLayout_4.addWidget(self.seSNRAnalysisLineEdit, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 3, 1)
        self.gridLayout_2.addWidget(self.buttonWidget, 11, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.mainframe)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 7, 3, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.mainframe)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_2.addWidget(self.widget_14, 1, 3, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.mainframe)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2.addWidget(self.widget_7, 5, 3, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.mainframe)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2.addWidget(self.widget_8, 3, 3, 1, 1)
        self.widget_15 = QtWidgets.QWidget(self.mainframe)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_2.addWidget(self.widget_15, 2, 3, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.mainframe)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2.addWidget(self.widget_5, 9, 3, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.mainframe)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2.addWidget(self.widget_6, 0, 3, 1, 1)
        self.widget_17 = QtWidgets.QWidget(self.mainframe)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_2.addWidget(self.widget_17, 9, 1, 1, 1)
        self.widget_16 = QtWidgets.QWidget(self.mainframe)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_2.addWidget(self.widget_16, 9, 2, 1, 1)
        self.cutouts = QtWidgets.QFrame(self.mainframe)
        self.cutouts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cutouts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cutouts.setObjectName("cutouts")
        self.cutoutsLayout = QtWidgets.QGridLayout(self.cutouts)
        self.cutoutsLayout.setObjectName("cutoutsLayout")
        self.dummyWidget = QtWidgets.QWidget(self.cutouts)
        self.dummyWidget.setObjectName("dummyWidget")
        self.cutoutsLayout.addWidget(self.dummyWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.cutouts, 0, 0, 8, 3)
        self.readoutframe = QtWidgets.QFrame(self.mainframe)
        self.readoutframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.readoutframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.readoutframe.setObjectName("readoutframe")
        self.readoutGridLayout = QtWidgets.QGridLayout(self.readoutframe)
        self.readoutGridLayout.setObjectName("readoutGridLayout")
        self.gridLayout_2.addWidget(self.readoutframe, 8, 0, 1, 3)
        self.gridLayout.addWidget(self.mainframe, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mrunSEButton.setText(_translate("Form", "Run SE"))
        self.mhelpButton.setText(_translate("Form", "Help"))
        self.mquitButton.setText(_translate("Form", "Quit"))
        self.label_3.setText(_translate("Form", "Box Size"))
        self.label.setText(_translate("Form", "SE threshold (0=none, 1=lots, default = 0.05)"))
        self.label_2.setText(_translate("Form", "SE SNR detect (default=2)"))
        self.label_4.setText(_translate("Form", "SE SNR analysis (default=2)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

